plugins: rubocop-rails

AllCops:
  TargetRailsVersion: 8.0
  TargetRubyVersion: 3.4
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  Enabled: true
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Exclude:
    - 'db/migrate/*'
