plugins: rubocop-rails

AllCops:
  TargetRailsVersion: 8.0
  TargetRubyVersion: 3.4
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
